/**
 * Created by kakato10 on 27.03.17.
 */
export default {
  AUTH_COMPLETED: 'AUTH_COMPLETED',
  REGISTER_USER: 'USER_REGISTERED',
  POST_CREATED: 'POST_CREATED',
  USERS_LOADED: 'USERS_LOADED',
  USER_FOLLOWED: 'USER_FOLLOWED',
  USER_UNFOLLOWED: 'USER_UNFOLLOWED',
  POSTS_LOADED: 'POSTS_LOADED',
  POST_LIKED: 'POST_LIKED'
}
