/**
 * Created by kakato10 on 27.03.17.
 */
export default {
  AUTH_COMPLETED: 'AUTH_COMPLETED',
  REGISTER_USER: 'USER_REGISTERED',
  POST_CREATED: 'POST_CREATED',
  USERS_LOADED: 'USERS_LOADED',
  USER_FOLLOWED: 'USER_FOLLOWED',
  USER_UNFOLLOWED: 'USER_UNFOLLOWED',
  POSTS_LOADED: 'POSTS_LOADED',
  POST_UPDATED: 'POST_UPDATED',
  COMMENT_CREATED: 'COMMENT_CREATED',
  COMMENTS_LOADED: 'COMMENTS_LOADED',
  POSTS_LOADED_BY_HASHTAG: 'POSTS_LOADED_BY_HASHTAG',
  USER_POSTS_LOADED: 'USER_POSTS_LOADED',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
  SETTINGS_LOADED: 'SETTINGS_LOADED',
  STATS_LOADED: 'STATS_LOADED',
  STATS_TRENDING_LOADED: 'STATS_TRENDING_LOADED'
}
